# name: 'Hello World'
# description: 'Greet someone'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
# runs:
#   using: "composite"
#   steps:
#     - run: echo Hello ${{ inputs.who-to-greet }}.
#       shell: bash
#     - id: random-number-generator
#       run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
#       shell: bash
#     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#       shell: bash
#     - run: goodbye.sh
#       shell: bash
name: 'Jenkins trigger build'
description: 'Auto trigger build of jenkins'
# branding:
#   icon: "check"
#   color: "green"
# inputs:
#   jenkins-url:  # url
#     description: 'URL of Jenkins server'
#     required: true
#   jenkins-job: #job name
#     description: 'Job name'
#     required: true
#   jenkins-user: #user name of jenkins
#     description: 'Jenkins user name'
#     required: true
#   jenkins-token:
#     description: 'Jenkins token'
#     required: true
runs:
  using: "composite"
  steps:
     - run: echo 'curl --silent -u admin:11ee65cf2ec4c69e0e255da6fda1c6c563 http://18.213.154.73:8080/job/Sonar/lastBuild/api/json | jq ".result"' 
       shell: bash
        
#     - run: curl -X POST http://${{ inputs.jenkins-url }}/job/${{ inputs.jenkins-job }}/build --user ${{ inputs.jenkins-user }}:${{ inputs.jenkins-token }}
 
    
